export declare type InitConfig = {
    jwtToken?: string;
    domain?: string;
    enableLog?: boolean;
    logSize?: number;
    bundleResPath?: string;
    appGroupId?: string;
    replaykitBundleIdentifier?: string;
};
export declare type MeetingSettingsConfig = {
    disableVideoPreview?: boolean;
    enableCustomizedMeetingUI?: boolean;
    disableClearWebKitCache?: boolean;
    language?: string;
};
export declare type JoinMeetingConfig = {
    userName: string;
    meetingNumber: string;
    password?: string;
    zoomAccessToken?: string;
    vanityID?: string;
    webinarToken?: string;
    joinToken?: string;
    appPrivilegeToken?: string;
    isMyVoiceInMix?: boolean;
    isAudioRawDataStereo?: boolean;
    noDrivingMode?: boolean;
    noInvite?: boolean;
    noMeetingEndMessage?: boolean;
    noMeetingErrorMessage?: boolean;
    noTitleBar?: boolean;
    noBottomToolbar?: boolean;
    noPhoneDialIn?: boolean;
    noPhoneDialOut?: boolean;
    noRecord?: boolean;
    noShare?: boolean;
    noVideo?: boolean;
    inviteOptions?: number;
    customerKey?: string;
    customMeetingId?: string;
    noUnmuteConfirmDialog?: boolean;
    noWebinarRegisterDialog?: boolean;
    noChatMsgToast?: boolean;
    noAudio?: boolean;
    meetingViewsOptions?: string;
};
export declare type StartMeetingConfig = {
    userName: string;
    meetingNumber?: string;
    userType?: number;
    inviteContactId?: string;
    zoomAccessToken: string;
    vanityID?: string;
    isMyVoiceInMix?: boolean;
    isAudioRawDataStereo?: boolean;
    noDrivingMode?: boolean;
    noInvite?: boolean;
    noMeetingEndMessage?: boolean;
    noMeetingErrorMessage?: boolean;
    noTitleBar?: boolean;
    noBottomToolbar?: boolean;
    noPhoneDialIn?: boolean;
    noPhoneDialOut?: boolean;
    noRecord?: boolean;
    noShare?: boolean;
    noVideo?: boolean;
    inviteOptions?: number;
    customerKey?: string;
    customMeetingId?: string;
    noUnmuteConfirmDialog?: boolean;
    noWebinarRegisterDialog?: boolean;
    noChatMsgToast?: boolean;
    noAudio?: boolean;
    meetingViewsOptions?: string;
};
export declare type ZoomSDKType = {
    initSDK: (config: InitConfig) => Promise<boolean>;
    joinMeeting: (config: JoinMeetingConfig) => Promise<number>;
    startMeeting: (config: StartMeetingConfig) => Promise<number>;
    updateMeetingSetting: (config: MeetingSettingsConfig) => void;
    isInitialized: () => Promise<boolean>;
};
export declare class ZoomSDK implements ZoomSDKType {
    initSDK(config: InitConfig): any;
    joinMeeting(config: JoinMeetingConfig): any;
    startMeeting(config: StartMeetingConfig): any;
    updateMeetingSetting: any;
    isInitialized: any;
}
